# KNN 알고리즘
iris 데이터 사용

In [ ]:
from sklearn.datasets import load_iris # iris 데이터 불러오기
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [ ]:
data = iris.data
target = iris.target # labels
print(data)
print(target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print(data.shape, target.shape)
# :Attribute Information:
#     - sepal length in cm
#     - sepal width in cm
#     - petal length in cm
#     - petal width in cm
#     - class:
#             - Iris-Setosa
#             - Iris-Versicolour
#             - Iris-Virginica

(150, 4) (150,)


In [ ]:
import numpy as np
np.unique(target, return_counts=True) # return_counts=True 각각의 유니크 값이 target에서 몇 번 나왔는지 확인

(array([0, 1, 2]), array([50, 50, 50]))

In [ ]:
from sklearn.model_selection import train_test_split # 데이터를 학습용과 테스트용 데이터로 나누는 함수
x_train, x_test, y_train, y_test = train_test_split(data, # 입력 데이터(꽃의 특징)
                                                    target, # 정답 레이블(꽃의 종류)
                                                    test_size=0.3, # 테스트 데이터셋의 크기를 결정, 0.25가 기본
                                                    stratify=target, # 모집단의 클래스 비율 유지 설정, target의 클래스 비율을 학습/테스트 데이터에도 동일하게 유지
                                                    random_state=0) # 랜덤 시드 설정 (결과 재현 가능성 확보용)
print(f"x_train : {x_train.shape}, y_test : {y_test.shape}")

x_train : (105, 4), y_test : (45,)


In [ ]:
np.unique(y_test, return_counts=True) # 클래스 비율이 고르게 분포되어 있지 않은 걸 확인(bias), 모델 평가가 왜곡될 가능성 있음

(array([0, 1, 2]), array([16, 18, 11]))

In [ ]:
np.unique(y_test, return_counts=True) # stratify=target를 통해 모집단의 클래스 비율 유지 설정했기 때문에 array([15, 15, 15] 나옴

(array([0, 1, 2]), array([15, 15, 15]))

KNN에는 Z-score 표준화가 더 적합

Min-Max Normalization는 range를 벗어날 경우가 생길 수 있으며, 이상치 혹은 훈련 범위를 벗어난 새로운 데이터에 매우 민감

In [ ]:
print(np.min(x_train, axis=0)) # 현재 shape(150, 4), 나는 4만 남는걸 원하기 때문에 = 열에 대한 값을 원하기 때문에 axis=0을 해줌
print(np.max(x_train, axis=0))
print(np.mean(x_train, axis=0))
print(np.std(x_train, axis=0))

[4.3 2.  1.  0.1]
[7.9 4.4 6.9 2.5]
[5.86380952 3.04190476 3.75714286 1.20095238]
[0.85725184 0.45288093 1.7976099  0.76201428]


z-score 스케일링 (표준화, Standardization) 데이터의 평균을 0, 표준편차를 1로 변환

직접 구현한 z-score 스케일링
- StandardScaler().fit(x_train).transform(x_train) 와 동일한 결과

In [ ]:
(x_train - np.mean(x_train, axis=0)) / np.std(x_train, axis=0)
# x_train (105,4), np.mean(x_train, axis=0) (4,) -> (105, 4)
# (값 - 평균) / 표준편차

array([[ 9.75431527e-01,  5.69896463e-01,  1.08080020e+00,
         1.70475496e+00],
       [ 2.14194987e+00,  1.67393943e+00,  1.63709442e+00,
         1.31106155e+00],
       [ 6.25476025e-01,  3.49087870e-01,  8.58282512e-01,
         1.44229269e+00],
       [-1.47425699e+00,  1.23232224e+00, -1.53378264e+00,
        -1.31356119e+00],
       [-7.74345984e-01,  7.90705055e-01, -1.31126495e+00,
        -1.31356119e+00],
       [-1.70756066e+00, -9.25293150e-02, -1.36689437e+00,
        -1.31356119e+00],
       [-1.12430149e+00, -1.41738087e+00, -2.54305930e-01,
        -2.63712094e-01],
       [ 6.25476025e-01, -7.54955092e-01,  8.58282512e-01,
         9.17368138e-01],
       [ 2.75520522e-01, -9.25293150e-02,  4.68876558e-01,
         2.61212453e-01],
       [ 1.09208336e+00, -9.25293150e-02,  9.69541356e-01,
         1.17983041e+00],
       [-1.24095332e+00, -9.25293150e-02, -1.31126495e+00,
        -1.18233005e+00],
       [ 5.08824191e-01,  5.69896463e-01,  5.24505980e-01,
      

StandardScaler를 활용한 z-score 스케일링

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train) # 데이터의 평균과 표준편차를 계산하여 저장

# fit에서 계산된 평균과 표준편차를 사용하여 x_train 데이터를 z-score 방식으로 표준화함
x_train_zst = scaler.transform(x_train)
# test는 fit을 사용하지 않는 이유 : test는 미래에 나올만한 데이터이기때문에 평균 표준편차를 모름, 데이터 누설을 방지
x_test_zst = scaler.transform(x_test)

print(x_train[:10])
print(x_train_zst[:5])

[[6.7 3.3 5.7 2.5]
 [7.7 3.8 6.7 2.2]
 [6.4 3.2 5.3 2.3]
 [4.6 3.6 1.  0.2]
 [5.2 3.4 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.9 2.4 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [6.1 3.  4.6 1.4]
 [6.8 3.  5.5 2.1]]
[[ 0.97543153  0.56989646  1.0808002   1.70475496]
 [ 2.14194987  1.67393943  1.63709442  1.31106155]
 [ 0.62547602  0.34908787  0.85828251  1.44229269]
 [-1.47425699  1.23232224 -1.53378264 -1.31356119]
 [-0.77434598  0.79070506 -1.31126495 -1.31356119]]


KNN 알고리즘

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# 모델 생성
iris_knn = KNeighborsClassifier(n_neighbors=10) # 사용할 이웃의 수
# 모델 학습
iris_knn.fit(x_train_zst, y_train) # (z-score로 표준화된 훈련 데이터, 해당 데이터의 라벨)

# 예측
pred = iris_knn.predict(x_test_zst)

In [ ]:
print(y_test)
print(pred)

[2 2 0 0 1 0 1 2 0 1 0 2 0 2 1 2 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 2 1
 0 0 1 0 2 0 0 2]
[2 2 0 0 1 0 1 1 0 1 0 2 0 2 1 2 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 1 1
 0 0 1 0 2 0 0 2]


In [ ]:
print(np.mean(y_test == pred))

0.9555555555555556


In [ ]:

  iris_knn = KNeighborsClassifier(n_neighbors=k)
  iris_knn.fit(x_train_zst, y_train)
  pred = iris_knn.predict(x_test_zst)
  print(k, "==>", np.mean(y_test == pred))

1 ==> 0.9555555555555556
2 ==> 0.9555555555555556
3 ==> 0.9777777777777777
4 ==> 0.9555555555555556
5 ==> 0.9777777777777777
6 ==> 0.9555555555555556
7 ==> 0.9777777777777777
8 ==> 0.9777777777777777
9 ==> 0.9777777777777777
10 ==> 0.9555555555555556
11 ==> 0.9777777777777777
12 ==> 0.9555555555555556
13 ==> 1.0
14 ==> 0.9333333333333333
15 ==> 0.9555555555555556
16 ==> 0.9333333333333333
17 ==> 0.9555555555555556
18 ==> 0.9555555555555556
19 ==> 0.9555555555555556
20 ==> 0.9111111111111111


In [ ]:
iris_knn = KNeighborsClassifier(n_neighbors=11)
iris_knn.fit(x_train_zst, y_train)
pred = iris_knn.predict(x_test_zst)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)
# 결과를 해석해보면 클래스 0: 15개 정확히 맞춤, 클래스 1: 15개 정확히 맞춤, 클래스 2: 14개 맞추고 1개는 클래스 1로 틀림

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 14]])