In [40]:
txt = 'hihello'
set(txt)

{'e', 'h', 'i', 'l', 'o'}

In [41]:
ch2id = {ch:id for id, ch in enumerate(set(txt))}
print(ch2id)
txt_id = [ch2id[ch] for ch in txt]
print(txt_id)

{'e': 0, 'o': 1, 'h': 2, 'l': 3, 'i': 4}
[2, 4, 2, 0, 3, 3, 1]


In [42]:
from tensorflow.keras.utils import to_categorical
data = to_categorical(txt_id)
print(data)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]


In [43]:
import numpy as np
x_data = data[:-1][np.newaxis,:,:] # hihell
y_data = data[1:][np.newaxis,:,:] # ihello
print(x_data.shape, y_data.shape)

(1, 6, 5) (1, 6, 5)


In [28]:
# 모델 만들기
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, SimpleRNN, LSTM

hihello_model = Sequential()
hihello_model.add(Input(shape=(6, 5))) # (배치,) 갯수, 크기
hihello_model.add(LSTM(units=16, return_sequences=True))
hihello_model.add(Dense(5, activation='softmax')) # Dense를 통해 shape 맞춤
hihello_model.summary()

hihello_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
hihello_model.fit(x_data, y_data, epochs=100)

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 6, 16)          │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6, 5)           │            85 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,493 (5.83 KB)

 Trainable params: 1,493 (5.83 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0000e+00 - loss: 1.6431
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.0000e+00 - loss: 1.6397
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.0000e+00 - loss: 1.6363
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0000e+00 - loss: 1.6329
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 1.6296
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.0000e+00 - loss: 1.6263
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.0000e+00 - loss: 1.6230
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.0000e+00 - loss: 1.6197
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0000e+00 - loss: 1.6165
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0000e+00 - loss: 1.6132
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.0000e+00 - loss: 1.6100
Epoch 12/100
1/1 ━━━━━━━━━━━━━━

In [29]:
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_test.shape)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(60000, 28, 28) (10000,)


In [30]:
np.max(x_train)

np.uint8(255)

In [31]:
x_train_norm = x_train / 255
x_test_norm = x_test / 255

y_train_oh = to_categorical(y_train)
y_test_oh = to_categorical(y_test)
print(np.max(x_train_norm), y_test_oh.shape)

1.0 (10000, 10)


In [32]:
x_train_norm.shape, y_train_oh.shape

((60000, 28, 28), (60000, 10))

In [38]:
# 모델 만들기 (LSTM의 결과가 잘 나오면 데이터의 성격이 시퀀스라는 걸 알 수 있음.)
mnist_lstm = Sequential()
mnist_lstm.add(Input(shape=(28, 28)))
mnist_lstm.add(LSTM(units=32)) # 마지막 시점의 출력만 반환
mnist_lstm.add(Dense(10, activation='softmax'))
mnist_lstm.summary()
mnist_lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
mnist_lstm.fit(x_train_norm, y_train_oh,
               validation_data=(x_test_norm, y_test_oh),
               epochs=2)

Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_6 (LSTM)                   │ (None, 32)             │         7,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,138 (31.79 KB)

 Trainable params: 8,138 (31.79 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 25s 12ms/step - accuracy: 0.6815 - loss: 1.0036 - val_accuracy: 0.9366 - val_loss: 0.2226
Epoch 2/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 40s 12ms/step - accuracy: 0.9417 - loss: 0.2014 - val_accuracy: 0.9575 - val_loss: 0.1501


In [55]:
docs = ['나는 당신을 사랑합니다', '나는 당신을 미워합니다', 'i love you', 'i hate you']
docs_tgt = ['i love you', 'i hate you', '나는 당신을 사랑합니다', '나는 당신을 미워합니다']

In [56]:
src_split = [doc.split() for doc in docs]
tgt_split = [doc.split() for doc in docs_tgt]

In [57]:
src_vocab = set()
for seq in src_split:
    src_vocab.update(seq)
src_vocab = sorted(src_vocab)
print("Source vocab:", src_vocab)

Source vocab: ['hate', 'i', 'love', 'you', '나는', '당신을', '미워합니다', '사랑합니다']


In [58]:
tgt_vocab = set()
for seq in tgt_split:
    tgt_vocab.update(seq)
tgt_vocab = sorted(tgt_vocab)
print("Target vocab:", tgt_vocab)

Target vocab: ['hate', 'i', 'love', 'you', '나는', '당신을', '미워합니다', '사랑합니다']


In [54]:
ch2id = {ch:id for id, ch in enumerate(vocab)}
print(ch2id)

{'you': 0, 'love': 1, 'hate': 2, '당신을': 3, '미워합니다': 4, 'i': 5, '나는': 6, '사랑합니다': 7}


In [ ]:
docs_model = Sequential()
docs_model.add(Input(shape=(3, 8)))
docs_model.add(LSTM(units=16, return_sequences=True))
docs_model.add(Dense(3, activation='softmax'))
docs_model.summary()

docs_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
docs_model.fit(x_data, y_data, epochs=100)

In [64]:
docs = ['나는 당신을 사랑합니다', '나는 당신을 미워합니다', 'i love you', 'i hate you']

wdlst = {}
for sent in docs:
  wdlst = set(wdlst).union(set(sent.split(' ')))
print(wdlst)
wd2id = {wd:id for id, wd in enumerate(wdlst)}
id2wd = {id:wd for id, wd in enumerate(wdlst)}
print(wd2id)
print(id2wd)

x_data=[]
for sent in docs:
  x_data.append([wd2id[wd] for wd in sent.split(' ')])
print(x_data)
x_data_oh = to_categorical(x_data)
print(x_data_oh.shape)
print(x_data_oh)

{'you', 'love', 'hate', '당신을', '미워합니다', 'i', '나는', '사랑합니다'}
{'you': 0, 'love': 1, 'hate': 2, '당신을': 3, '미워합니다': 4, 'i': 5, '나는': 6, '사랑합니다': 7}
{0: 'you', 1: 'love', 2: 'hate', 3: '당신을', 4: '미워합니다', 5: 'i', 6: '나는', 7: '사랑합니다'}
[[6, 3, 7], [6, 3, 4], [5, 1, 0], [5, 2, 0]]
(4, 3, 8)
[[[0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]]]


In [70]:
translate_model = Sequential()
translate_model.add(Input(shape=(3, 8)))
translate_model.add(LSTM(32, return_sequences=True))
translate_model.add(Dense(8, activation='softmax'))
translate_model.summary()

translate_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# 한글 -> 영어
translate_model.fit(x_data_oh[:2], x_data_oh[2:], epochs=100)
pred = translate_model.predict(x_data_oh[:2])
# 영어 -> 한글
# translate_model.fit(x_data_oh[2:], x_data_oh[:2], epochs=100)
# pred = translate_model.predict(x_data_oh[2:])
print(np.argmax(pred, axis=2))

Model: "sequential_24"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_12 (LSTM)                  │ (None, 3, 32)          │         5,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3, 8)           │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,512 (21.53 KB)

 Trainable params: 5,512 (21.53 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1667 - loss: 2.0811
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1667 - loss: 2.0758
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.1667 - loss: 2.0706
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.1667 - loss: 2.0653
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.1667 - loss: 2.0601
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.1667 - loss: 2.0549
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.1667 - loss: 2.0497
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3333 - loss: 2.0445
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3333 - loss: 2.0393
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.3333 - loss: 2.0341
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 2.0289
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step
[[6 3 7]
 [6 3 4]]


- 현재 모델은 정확도가 50%임 그 이유는 영어와 한글의 어순차이 때문임
- 그렇기 때문에 한글 -> 영어는 정확도가 낮지만
- 영어 -> 한글로 하면 정확도가 높음

In [71]:
from tensorflow.keras.layers import Bidirectional

translate_model = Sequential()
translate_model.add(Input(shape=(3, 8)))
translate_model.add(Bidirectional(LSTM(32, return_sequences=True)))
translate_model.add(Dense(8, activation='softmax'))
translate_model.summary()

translate_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
translate_model.fit(x_data_oh[:2], x_data_oh[2:], epochs=100)
pred = translate_model.predict(x_data_oh[:2])
print(np.argmax(pred, axis=2))

Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)   │ (None, 3, 64)          │        10,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 3, 8)           │           520 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,016 (43.03 KB)

 Trainable params: 11,016 (43.03 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.0000e+00 - loss: 2.0754
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.0000e+00 - loss: 2.0677
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.0000e+00 - loss: 2.0601
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.1667 - loss: 2.0524
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.1667 - loss: 2.0448
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.3333 - loss: 2.0372
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 2.0296
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 2.0219
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6667 - loss: 2.0143
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6667 - loss: 2.0067
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 1.9991
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 563ms/step
[[5 0 0]
 [5 5 0]]
